
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./clickhouse/init:/docker-entrypoint-initdb.d

  debezium:
    image: debezium/connect:2.7.0.Final
    container_name: debezium
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      REST_PORT: 8083
    ports:
      - "8083:8083"
    volumes:
      - ./debezium/connectors:/connectors
      - ./debezium/scripts/init_connectors.sh:/docker-entrypoint-initdb.d/init_connectors.sh

  # airflow:
  #   build:
  #     context: ./airflow
  #     dockerfile: Dockerfile
  #   container_name: airflow
  #   depends_on:
  #     - clickhouse
  #     - kafka
  #     - debezium
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__CORE__LOAD_EXAMPLES=False
  #     - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:///airflow.db
  #     - PG_HOST=${PG_HOST}
  #     - PG_PORT=${PG_PORT}
  #     - PG_DB=${PG_DB}
  #     - PG_USER=${PG_USER}
  #     - PG_PASS=${PG_PASS}
  #     - CH_HOST=${CH_HOST}
  #     - CH_PORT=${CH_PORT}
  #     - CH_USER=${CH_USER}
  #     - CH_PASS=${CH_PASS}
  #     - CH_DB=${CH_DB}
  #     - DEBEZIUM_URL=${DEBEZIUM_URL}
  #     - KAFKA_BROKER=${KAFKA_BROKER}
  #     - CDC_CONSUMER_GROUP=${CDC_CONSUMER_GROUP}
  #   ports:
  #     - "8080:8080"
  #   command: >
  #     bash -c "airflow db init &&
  #              airflow users create --username admin --firstname Air --lastname Flow --role Admin --email admin@example.com --password admin &&
  #              airflow webserver & airflow scheduler"
  #   volumes:
  #     - ./airflow/dags:/opt/airflow/dags
  #     - ./dbt:/opt/airflow/dbt
  #     - ./clickhouse/init:/docker-entrypoint-initdb.d



  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      - clickhouse
      - kafka
      - debezium
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      # AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/${PG_DB}?sslmode=require
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/${PG_DB}?sslmode=verify-full&sslrootcert=/opt/airflow/.postgresql/root.crt"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      # AIRFLOW__WEBSERVER__RBAC: "True"
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      CH_HOST: ${CH_HOST}
      CH_PORT: ${CH_PORT}
      CH_USER: ${CH_USER}
      CH_PASS: ${CH_PASS}
      CH_DB: ${CH_DB}
      DEBEZIUM_URL: ${DEBEZIUM_URL}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CDC_CONSUMER_GROUP: ${CDC_CONSUMER_GROUP}
    ports:
      - "8080:8080"
    volumes:
      - ./postgres-certs:/opt/airflow/.postgresql
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
        --username admin
        --firstname Air
        --lastname Flow
        --role Admin
        --email admin@example.com
        --password admin || true &&
      exec airflow webserver --port 8080 --host 0.0.0.0"






